# Generated by Django 6.1.1 on 2026-09-10 12:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='скидка (в процентах)')),
                ('category', models.CharField(choices=[('electronics', 'Электроника'), ('clothe', 'Одежда'), ('books', 'Книга'), ('food', 'Еда'), ('other', 'другое')], default='other', max_length=50, verbose_name='Категория')),
                ('in_have', models.BooleanField(default=True, verbose_name='есть ли в наличии')),
            ],
        ),
    ]
